### ISSUE TITLE
Is there any methods to handle choosing entriesOptions in mdbootstrap datatable?

### ISSUE THREAD

**Issue by diarfathur** [mdbootstrap/mdb-docs-and-content#36]
I've been looking on API References in mdbootstrap datatables, but I can't find any methods to handle choosing entriesOptions (size of entries : [10, 25, 50,100])

**Comment by smolenski-mikolaj** [comment]
There is a key **entriesOptions** which is an array:
**entriesOptions** | Array | [10, 25, 50, 200] | Options available to choose from in a pagination select (rows per page)
