### ISSUE TITLE
Spelling error in  mdb-docs-and-content/en/react/web/docs/navigation/link/o.html 

### ISSUE THREAD

**Issue by 0xRenegade** [mdbootstrap/mdb-docs-and-content#39]
mdb-docs-and-content/en/react/web/docs/navigation/link/o.html

Contains small typo here: pacakge => package
and here: breake => break

**Comment by catchmareck** [comment]
Feel free to open a PR with fixes. Help in improving our docs is much appreciated ;)

**Comment by Iceberg1109** [comment]
I think it should be "will be broken", not "will be break".

**Comment by smolenski-mikolaj** [comment]
PR with this issue was merged.
