### ISSUE TITLE
Wrong option name in toasts API for MD5

### ISSUE THREAD

**Issue by MichaelBelgium** [mdbootstrap/mdb-docs-and-content#44]
[Link](https://mdbootstrap.com/docs/standard/components/toasts/#api-section-options)

"Content" isn't the right option for setting delay.

Name | Type | Default | Description
-- | -- | -- | --
content | number | 500 | Delay hiding the toast (ms)

It's "delay"

Name | Type | Default | Description
-- | -- | -- | --
delay | number | 500 | Delay hiding the toast (ms)

Found out after seeing "content" didn't work and checked the Toast js component out

**Comment by smolenski-mikolaj** [comment]
Thanks for remarks. We've already fixed the issue.
