### ISSUE TITLE
Table Sorting Issue

### ISSUE THREAD

**Issue by s2t2** [mdbootstrap/mdb-docs-and-content#48]
Hi, thanks for the cool sortable table component. The code referenced here https://mdbootstrap.com/docs/react/tables/sort/ produces a table, and when you click on a column it sorts ascending on that column, but subsequent clicks don't sort descending.

Please advise. Thanks. Details below.

Versions:

```js
  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "mdbreact": "^4.27.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.3"
```

Code:

```js
import React from 'react';
import { MDBDataTable } from 'mdbreact';

const DatatablePage = () => {
  const data = {
    // abbreviated :-D
  };

  return (
    <MDBDataTable
      striped
      bordered
      small
      data={data}
    />
  );
}

export default DatatablePage;

```

**Comment by krzysiu-w** [comment]
Hi!

I see you have MDB React package with version 4.27.0, while currently, it is 5.0.1. As you can see in our changelog (https://mdbootstrap.com/docs/react/changelog/) - some problems with data tables have been fixed. I also tested your code (using data from our documentation) and everything works as expected, so I recommend upgrading the package version :)

Best regards
