### ISSUE TITLE
content is hidden

### ISSUE THREAD

**Issue by KES777** [mdbootstrap/mdb-docs-and-content#90]
https://dashboard.mdbgo.com/#/home

Linux Mint 19.3, FF v87

![image](https://user-images.githubusercontent.com/799021/123142775-76cd9480-d462-11eb-9e50-d0bf8f3ff0b7.png)

**Comment by smolenski-mikolaj** [comment]
Thanks for posting an issue. We have already fixed it and an update will be released soon.

Keep coding, 
Mikołaj from MDB

**Comment by KES777** [comment]
thank you
