### ISSUE TITLE
Rendering <code> tag in html

### ISSUE THREAD

**Issue by sheikhmishar** [mdbootstrap/mdb-docs-and-content#95]
Hello there, I have been trying to use this doc for offline use as I have a limited data connectivity. So far, I haven't been able to render the codes with syntax highlighting. Also, I have been rendering html in hacky way. Is there any proper way of rendering the whole html?

**Comment by smolenski-mikolaj** [comment]
The documentation is prepared to run only on the mdbootstrap.com website.
