### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by KES777** [mdbootstrap/mdb-docs-and-content#97]
https://mdbootstrap.com/legacy/4.3.2/?page=css/layout#grid-classes

![image](https://user-images.githubusercontent.com/799021/133066253-af0b2ace-43ac-4db7-8c55-8b2ea9439094.png)

**Comment by smolenski-mikolaj** [comment]
Please open a new issue on our [support forum](https://mdbootstrap.com/support)

**Comment by KES777** [comment]
From support forum I can not track issue state
