### ISSUE TITLE
Broken documentation

### ISSUE THREAD

**Issue by KES777** [mdbootstrap/mdb-docs-and-content#98]
https://mdbootstrap.com/articles/jquery/md-bootstrap-webpack-tutorial/

![image](https://user-images.githubusercontent.com/799021/133888176-6ad22256-65e0-4682-a0a6-b41093bb3cf8.png)

**Comment by smolenski-mikolaj** [comment]
Please open a new issue on our [support forum](https://mdbootstrap.com/support)
